### PR TITLE
Hint on max. 64 characters for firmware filenames

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by ilario** [comment]
So it's a bug in the original tp-link firmware interface...
https://forum.openwrt.org/viewtopic.php?pid=334978#p334978
+1 for merge

**Comment by rubo77** [comment]
alternatively you could create symlinks  in your download folder with shorter names to the tp-link images that have too long names

**Comment by G10h4ck** [comment]
This doesn't affect all router models so this addition should reflect this with something like "be aware that in some router models..."

**Comment by rubo77** [comment]
maybe you should completely get rid of the ending "-factoroy", cause only those are relevant if you want to flash a new tp-link router

**Comment by ilario** [comment]
@rubo77 I would not remove the "-factory", better to stay close to OpenWrt/LEDE defaults...
This is going to be solved with next release as it will be LEDE based and with shorter filenames.
Until then I would add this information in the documentation/hardware page, not in the getit page.

I just confirmed the bug on TP-Link WDR3600 with factory firmware: OpenWrt factory image for WDR3600 is 66 char long and is not accepted by the tp-link web interface.

**Comment by rubo77** [comment]
If you hide it anywhere else than directly next to the download link, many users will not read it. And until this is fixed, it is essential to be able to flash your device.

I would add it there

**Comment by ilario** [comment]
Ok, let's merge, later I will add some text for specifying that affects just TP-Link.

**Comment by ilario** [comment]
No idea how or why but this was reverted by 3cc1eb8fe0a7c74534f9eea0f12e80fdb0272a34 or 590cffc787f830b2570816cfdb5cc71b7d69c059
@p4u ?

**Pull request merged**
