### PR TITLE
add router models to quick starting guide

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by ilario** [comment]
+1 for the "-sysupgrade" vs "-factory" fix.

We should discuss about having the hardware list... Was your idea to put there all the routers in the [lime-build targets](https://github.com/libremesh/lime-build/tree/develop/targets)? Or shall we put there the routers we tested in real world? @p4u suggestions?

**Comment by rubo77** [comment]
I would suggest to put there some routers, you can recommend to use and a like to a list with all supported routers

**Comment by ilario** [comment]
Makes sense. 
So, just tested routers (surveying the users) or all routers for which the images are provided?

**Comment by p4u** [comment]
@rubo77  It is not correct that libre-mesh is only compatible with 8MB flash routers. It can also be used in 4MB devices by using the special target for small routers like [ar71xx-mini](http://downloads.libre-mesh.org/community_chaos/16.07/ar71xx-mini/generic/). However it is true that at least 8MB is recommended.

@ilario there are not specific router targets in lime-build, but only specific architectures such as ar71xx

In any case I think it is a good idea to add a list of "tested" hardware,  but it should be clear that not being in the list does not mean to be incompatible with libre-mesh.

**Comment by ilario** [comment]
I merge, then I will clean up a bit because it will be messed because of merge of #19.

**Pull request merged**
