### PR TITLE
Replaces old chef with new chef in URLs Fixes #38

### LINKED ISSUE #38: Replace references to Chef with https://chef.libremesh.org
https://chef.libremesh.org is now working and replaces outdated Chef

### PR DESCRIPTION
**Pull request by svalo**
Title pretty self-explanatory :)
It is based on current master

### CODE REVIEW

**Comment by ilario** [comment]
Thanks for addressing this, the PR will be stalling for a while 'cause we're making our minds on how the new online Cooker should be named... See libremesh/lime-sdk#34 and aparcar/jefe#13
In the meanwhile I could make some suggestions :D

* I would use the URL https://imagebuilder.libremesh.org/imagebuilder as points directly to the correct tab
* the text "does not support the latest stable release, up to now it can be used just for previous release." is not correct with the new stuff

**Comment by svalo** [comment]
Thank for the feedback @ilario I'll wait for the discussion and then adjust this PR accordingly

**Comment by ilario** [comment]
The discussion resulted in the new name being "chef", as the previous software. So the new direction will be chef.libremesh.org (the redirect is not yet active)

**Comment by ilario** [comment]
@svalo finally the https://chef.libremesh.org is online :D

**Comment by svalo** [comment]
Great! I'll modify also the sorrounding text, would it be fine to add the link to chef to the bullet list of the available methods?
I noticed also on the "get it" page there is a reference to chef, it is marked as outdated, I'll edit that one as well.

**Comment by ilario** [comment]
That looks great! Thanks @svalo! Merging :D

**Pull request merged**
