### PR TITLE
add italian translation Quick starting guide

### PR DESCRIPTION
**Pull request by digitigrafo**
using this way: https://www.sylvaindurand.org/making-jekyll-multilingual/

### CODE REVIEW

**Comment by nicopace** [comment]
Thanks for tue pull request.
Will review it ASAP.

**Comment by nicopace** [comment]
Excelent!
for me it makes sense to have global support for multiple languages and if there is no page show the default english page... don't know if that is possible or not.
But it is hard to find the translate top bar if you don't know it is there, isn't it?
What do you think  @digitigrafo ?

**Comment by digitigrafo** [comment]
Il 03/07/17 11:00, Nicolás Pace ha scritto:
>
> Excelent!
> for me it makes sense to have global support for multiple languages 
> and if there is no page show the default english page... don't know if 
> that is possible or not.
> But it is hard to find the translate top bar if you don't know it is 
> there, isn't it?
> What do you think @digitigrafo <https://github.com/digitigrafo> ?
>
yeh, we can show the same "switch" en/It/.. in all the pages (maybe a 
bit more cool), to help people undestarnd that some pages are translated.
I can try on a mockup

**Comment by nicopace** [comment]
Excelent! Will be around to review it so we can do fast iterations :)

**Comment by ilario** [comment]
I tested locally and it's great :D
But I didn't spot where "En | It" was at first sight, maybe when it will be sitewide it will be more evident?
Otherwise we could change the background color of "En | It" from black to something else?

**Comment by nicopace** [comment]
Or instead of appearing on the upper left corner, it could appear exactly next to the logo, so it is more evident that affects all the site

**Comment by digitigrafo** [comment]
Il 03/07/17 17:10, Ilario Gelmetti ha scritto:
>
> I tested locally and it's great :D
> But I didn't spot where "En | It" was at first sight, maybe when it 
> will be sitewide it will be more evident?
> Otherwise we could change the background color of "En | It" from black 
> to something else?
>

yes, I also saw that when is in mobile the "En | It" stay inside the 
scroll menu, and this is not really good.
I think is better put it outside the scroll menu, but inside nav top layout

**Comment by ilario** [comment]
Another topic: Instead of adding all files in the `docs` directory with the localized name I would either:

- add them with a prefix (in this case "IT-")
- add them in a subdir

Consider that this decision will affect also which files will be included in firmware images, as files .txt directly in `docs` dir are copied in firmware by `lime-docs` package while files in subdirectories are not.

**Comment by nicopace** [comment]
@ilario I think it is all in @digitigrafo hands... if he can make it... great! if not, we can do iterative improvements :)

Actually.. the lime-docs package could list all the regional packages by name or even by content grepping each file... so it is not that of a problem.

Would be nice although :)

**Comment by ilario** [comment]
@nicopace do you mean we should make `lime-docs-it`, `lime-docs-es`...?
In this case I would suggest to use a subdirectory for each language.

**Comment by digitigrafo** [comment]
large_menu
mini_menu
new place, new style.

**Comment by ilario** [comment]
@digitigrafo @nicopace 
 Another good option is to make `libremesh.org/it/`, `libremesh.org/es/`... subdirectories on the root of the website

**Comment by nicopace** [comment]
Another relevant thing, if you have time :) 
Would be to integrate it with transiflex.
that way would be much easier for non-technical users to contribute with translations.

BTW thank you @digitigrafo for all your collaboration on this! how do you think we can proceed?

**Comment by digitigrafo** [comment]
Il 04/07/2017 23:13, Ilario Gelmetti ha scritto:
>
> @digitigrafo <https://github.com/digitigrafo> @nicopace
> <https://github.com/nicopace>
> Another good option is to make |libremesh.org/it/|,
> |libremesh.org/es/|... subdirectories on the root of the website
>
please explain better..
in that way.. we will have different websites for languages.. and
duplicated or more, all the resources..
?

**Comment by p4u** [comment]
Even if it is not the best final solution it might be worth to add it. Is it ready to be merged?

**Comment by nicopace** [comment]
I'm not against merging it... but if @digitigrafo wants to enhance the solution before, better :) 
Also to leave this conversation channel open :)

**Comment by digitigrafo** [comment]
Il 05/07/2017 10:02, Nicolás Pace ha scritto:
>
> Another relevant thing, if you have time :)
> Would be to integrate it with transiflex.
> that way would be much easier for non-technical users to contribute
> with translations.
>
hum.. this step open a discussion..
transifex is not more a open source project..
end I'm not happy to use it.
I know also that still debian is using.. but I think is a mistake.
i can suggest this https://weblate.org/en/
>
> BTW thank you @digitigrafo <https://github.com/digitigrafo> for all
> your collaboration on this! how do you think we can proceed?
>
:) now we have only one translation, in only one language.. I think that
we can use the lighter way.
and after have a meeting and speak together about it.
Add a paragraph Translation in the page about contribution...

**Comment by nicopace** [comment]
Nice knowing about weblate! do u know if it is integratable?

Also, we have people from different countries that want to collaborate (French, Portuguese, Spanish, Swagili, arabic) but we need to make them easy to do it in order for them to mantain it mainly.

**Comment by digitigrafo** [comment]
Weblate currently supports Git (with extended support for GitHub) as version control backends.
maybe the merge conflict could be an hell.. i dont know.
but i'll begin to use in another project.. so I'll tell you how it works.
for the translators appears in this way:
weblate

**Comment by nicopace** [comment]
Ok... we may merge this change and then see if we migrate to another thing... 
Do u agree?

**Comment by nicopace** [comment]
This issue from the f-droid project is very detailed on how to approach the problem:
https://gitlab.com/fdroid/fdroid-website/issues/15

**Comment by digitigrafo** [comment]
yes, i'm agree.

**Comment by ilario** [comment]
@digitigrafo what I care about is to be able to distinguish between documentation in different languages without having to grep the content, so:

* libremesh.org/docs/ **it-** guida_rapida_per_iniziare.html
* libremesh.org/docs/ **it-** quick_starting_guide.html
* libremesh.org/docs/quick_starting_guide **-it** .html
* libremesh.org/ **it/** docs/guida_rapida_per_iniziare.html
* libremesh.org/ **it/** docs/quick_starting_guide.html
* libremesh.org/docs/ **it/** guida_rapida_per_iniziare.html
* libremesh.org/docs/ **it/** quick_starting_guide.html

are all good solutions for me.

**Comment by digitigrafo** [comment]
Il 05/07/2017 14:24, Ilario Gelmetti ha scritto:
>
> @digitigrafo <https://github.com/digitigrafo> what I care about is to
> be able to distinguish between documentation in different languages
> without having to grep the content, so:
>
>   * libremesh.org/docs/ *it-* guida_rapida_per_iniziare.html
>   * libremesh.org/docs/ *it-* quick_starting_guide.html
>   * libremesh.org/docs/quick_starting_guide *-it* .html
>   * libremesh.org/ *it/* docs/guida_rapida_per_iniziare.html
>   * libremesh.org/ *it/* docs/quick_starting_guide.html
>   * libremesh.org/docs/ *it/* guida_rapida_per_iniziare.html
>   * libremesh.org/docs/ *it/* quick_starting_guide.html
>
> are all good solutions for me.
>
ok the first way.
it's in mine last commit.
but only in the directory doc, when we began translate.. in the future
we will change method. we said..
and the files will become.. namefile.it.po  namefile.fr.po 
probably :)

**Comment by nicopace** [comment]
great... thanks @digitigrafo

**Comment by p4u** [comment]
I would revert commit 7360929 "changed name file in doc with language prefix".

Firstly it breaks lime-docs package (cause config.txt does not exist anymore), thus it breaks the current libremesh compilation.

Secondly I would prefer to have a "default/master" (English by default) file and IMO it should not have any suffix name. So it is more clear and easy to understand that the rest of files are translations of this "default" file.

**Comment by ilario** [comment]
Soooorry I forgot to fix lime-docs, I'm going to do it now.

I would not revert commit 7360929 because it is needed by lime-docs for selecting just one language. If the english documentation had no prefix I wouldn't know how to selectively include it in lime-docs

**Comment by nicopace** [comment]
Related with https://github.com/libremesh/lime-packages/pull/176

**Comment by patogit** [comment]
_(In case you don't know me: I'm coordinating or advancing the translation of the software and documentation for the LibreRouter project, with the goal of making it easy for people to translate the project into many languages, and for people the use and contribute to the project in many languages.)_

I see that the content of the Documentation page at LibreMesh.org is available in Italian, but the sidebar and menus remain in English (and the dark grey header is larger on that page, some CSS error I imagine). Based on the experience setting up the Italian page, do we want to use the same method to translate the site into other languages? Is Jekyll still meeting our needs for LibreMesh.org?

The file layout of the website content is more like documentation than like a software interface. For translating the LibreRouter documentation, we haven't chosen a platform or workflow yet. Options include using [TranslateWiki](www.translatewiki.net) (what we plan to use for software interfaces), [Zanata](http://zanata.org/) (another online platform, it supports more file formats that TranslateWiki), desktop software like [OmegaT](https://en.wikipedia.org/wiki/OmegaT), or just doing it by hand. (Weblate didn't seem to work very well last time I tried it, but maybe it's an option.)

To use TranslateWiki, we might have to make a parser-generator for asciidoc (based on [SimpleFFS](https://github.com/wikimedia/mediawiki-extensions-Translate/blob/master/ffs/SimpleFFS.php)), and doing that might be useful for other LibreRouter documentation and other projects.

**Comment by ilario** [comment]
@patogit can you open a new issue for discussing this?

**Comment by patogit** [comment]
Can we use #22 ?
#23 was the same, and is closed.
Or we could close #22 and open a new issue.

**Comment by ilario** [comment]
@patogit you're right, let's use one of those two.

**Comment by patogit** [comment]
reposted at #22

**Pull request merged**
