### PR TITLE
Update SSID documentation

### LINKED ISSUE #60: Please clarify prefixes ap, apname, adhoc for _ssid
The web site does not clearly explain what the ap, apname, adhoc prefixes are used for in the LibreMesh config

Example (probably wrong):
- apname_ssid: Per access point unique SSID to avoid roaming (switching) between various access points that share an SSID
  https://github.com/libremesh/lime-packages/commit/a17e6170e838a29dcd0b65bde1fa0906b0898333
- ap_ssid: ?The SSID for consumer device access
  This is used as network / cloud identifier, and therefore BATADV VLAN is based on this setting.
  Access points that share the same ap_ssid will act like a single LAN
- adhoc_ssid: ?The mesh link used between access points

https://github.com/libremesh/lime-packages/blob/develop/packages/lime-docs/files/lime-example

https://github.com/libremesh/lime-web/blob/e37588650a94eaeab44ce2d8246e097886e18d6a/docs/en_config.txt#L103

https://github.com/libremesh/lime-web/blob/e37588650a94eaeab44ce2d8246e097886e18d6a/howitworks.txt#L53

A mention that this is the `config lime wifi` `ap_ssid` might make it more clear?

Cheers

### PR DESCRIPTION
**Pull request by sanadora**
This is an attempt to resolve #60 .

If the description of each SSID is okay to you, the next step would be to put them on the [lime-example](https://github.com/libremesh/lime-packages/blob/7bb258ef33838da443bb0e6fa7bdf8b5e694deeb/packages/lime-docs/files/lime-example#L78-L82) file.

### CODE REVIEW

**Comment by ilario** [comment]
Thanks!
A few small things:
I thinks that "It's hash" should be "Its hash" instead;
I would specify that adhoc_ssid is useful only when using adhoc and ignored when using ieee802.11s
The rest is ok! :D

**Comment by sanadora** [comment]
As always, thanks @ilario for your support!! 
I've just made both changes.

**Comment by ilario** [comment]
Great! Thanks! Could you do a similar pull request for lime-example?

**Comment by sanadora** [comment]
Yes, I will be glad to do it!

**Pull request merged**
