### PR TITLE
development: add note for having the OpenWrt kernel vermagic

### PR DESCRIPTION
**Pull request by ilario**
Read here for more details:
https://lists.libremesh.org/pipermail/lime-users/2020-September/001682.html

If you can, confirm that this works on your router.

### CODE REVIEW

**Comment by ilario** [comment]
Can anyone test this on different targets? @jkimmel @aparcar @spiccinini @G10h4ck @germanferrero
I tested it just with ramips/mt7621.
The way to test is:
compile following these additional instructions,
flash your router,
connect your router to the internet (e.g. connect its WAN port to your modem),
log into your router and try to install some package that depends on the kernel, like `tc` or `luci`.

**Comment by jkimmel** [comment]
libremesh test

Installing tc via luc,i opkg seemed freezing
Installing via cli successfull

**Comment by jkimmel** [comment]
But with version: r14668-a90f491ab4 (staging.dangole.git) I got
root@d948:~# opkg install tc
Installing tc (5.8.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/tc_5.8.0-1_mipsel_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for tc:
 *      kernel (= 5.4.70-1-9b76e0b464f2696dff83f006732f0156)
 * opkg_install_cmd: Cannot install package tc.

**Comment by ilario** [comment]
> Installing tc via luci, opkg seemed freezing
> Installing via cli successfull

Weeeeeird!
I didn't try the installation via LuCI (as in the next release the LuCI inclusion will not be supported) but I'm going to try now.

> But with version: r14668-a90f491ab4 (staging.dangole.git) I got
> root@d948:~# opkg install tc
> Installing tc (5.8.0-1) to root...
> Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/tc_5.8.0-1_mipsel_24kc.ipk
> Collected errors:
> 
>     * satisfy_dependencies_for: Cannot satisfy the following dependencies for tc:
> 
>     * ```
>        kernel (= 5.4.70-1-9b76e0b464f2696dff83f006732f0156)
>       ```
> 
>     * opkg_install_cmd: Cannot install package tc.

Gosh, you're trying to install a package from the snapshots repositories from Daniel Golle, it's not as clean as working with an official OpenWrt released version. I don't even know where is it going to look for the kmod-sched-core package (which is a dependency of tc and which depends on the kernel).
I think we can be happy if we fix this for OpenWrt released versions.

**Comment by ilario** [comment]
I was testing on a ATH79 target (TP-Link WDR3600) and the instructions I wrote are not enough.
In that case, I had to select a multiprofile compilation and add also:

* Winchannel WB2000
* ZBT WD323

I will investigate further to understand why.

I will change the PR to point to a specific page where the cases are listed on a (sub)target by (sub)target case.

**Comment by ilario** [comment]
Regarding the Winchannel WB2000 this is likely happening due to some of these:
https://github.com/openwrt/openwrt/blob/openwrt-19.07/target/linux/ath79/image/generic.mk#L705
and regarding the ZBT WD323 is likely happening due to some of these:
https://github.com/openwrt/openwrt/blob/openwrt-19.07/target/linux/ath79/image/generic.mk#L750-L751
so I have to check which of these is not included by default:
kmod-i2c-core
kmod-i2c-gpio
kmod-rtc-pcf8563
kmod-rtc-ds1307
kmod-usb2
kmod-usb-serial
kmod-usb-serial-cp210x 
kmod-usb-ledtrig-usbport

**Comment by ilario** [comment]
After selecting also 
Kernel modules / Other modules / kmod-rtc-pcf8563
Kernel modules / Other modules / kmod-rtc-ds1307
I was able to compile a compatible ATH79/generic image for my TP-Link WDR3600.

Thus, from the command line I was able to install the `luci` package :D

And then, opening the LuCI interface from http://thisnode.info/cgi-bin/luci I tried to install the `tc` package and the interface was weirdly stuck on a "Executing package manager" message. Anyway, checking from SSH, tc was actually installed, so it works!! Waiting some time and reloading the page showed the tc package installed.
Can you check if this is also your case?

I'm going to create the separate page for the subtarget-specific information collection.
I'll take your report as to mean that for `MediaTek Ralink MIPS / MT7620 based boards` the instructions in this PR are enough, correct?

**Comment by ilario** [comment]
I added a huge bunch of instructions, I'm going to merge but we can go on discussing here further modifications.

**Comment by jkimmel** [comment]
Powered by LuCI openwrt-19.07 branch (git-20.247.75781-0d0ab01) / LiMe
master development (master rev. 2c4b783 20201001_1200)

  Yes, same here. While installing tc from Luci Executing package manager
got stuck. Installing from cli no problem.

Am Mi., 14. Okt. 2020 um 21:30 Uhr schrieb Ilario Gelmetti <
notifications@github.com>:

**Comment by ilario** [comment]
> While installing tc from Luci Executing package manager got stuck.

Could be a LuCI issue.
To me it happened installing also other packages, but not always.
Anyway the packages get installed correctly even if no confirmation is shown.

**Pull request merged**
