### PR TITLE
en_vim-guide.txt

### PR DESCRIPTION
**Pull request by panosnethood**
I did a first draft of a "very short" vim tutorial. 

I copied the markup from other files and I hope it works. Of course feel free to edit!

It is also the first time I do a pull request from a fork. I hope it is correct :-)

### CODE REVIEW

**Comment by ilario** [comment]
This looks very good, thanks! It's even a `vi` guide, not a `vim` guide as expected! :)
Just one correction: you need to leave a blank line before the itemized lists in order to have them recognized as such.
And maybe rather than putting code between " (for example ":wq") you could use + (for example +:wq+) for having it represented as code.

**Comment by panosnethood** [comment]
Done! How could I see how it looks?

**Comment by ilario** [comment]
Mh, I meant a blank line before the whole block of the itemized lists, not only each item. I could just test locally with Jekyll but I'm having problems with it at the moment. I merge and if the itemized list will be broken I just remove the additional blank lines :)

**Comment by ilario** [comment]
I don't know why but the HTML is not being generated.
Can anyone having a working Jekyll installation check? @nicopace @aparcar @p4u 
Maybe Jekyll doesn't like the blank line at the beginning of the file?

**Comment by nicopace** [comment]
I am using the docker version and it is not generating.
Anyone with experience with jekyll can help here? @libremesh/owners

**Comment by ilario** [comment]
@nicopace can you test if it gets generated after deleting the blank line at the beginning of the txt file?
Otherwise it will be because it's not linked in any other file I suppose.

**Comment by nicopace** [comment]
Yes... it was that. I already fixed this in master.
Thanks @ilario !

**Comment by ilario** [comment]
Amazing, finally we have it! http://libremesh.org/docs/en_vim-guide.html

**Comment by panosnethood** [comment]
Great! I had in mind to try a slightly improved version with a few more commands like dd or :#line but perhaps there are not needed for editing config files :-)

**Pull request merged**
