### PR TITLE
add wget to dependencies

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by ilario** [comment]
+1 for merge. Did you check that is needed?
Anyway looks needed looking at OpenWrt buildroot requirements: 
https://wiki.openwrt.org/doc/howto/buildroot.exigence

**Comment by rubo77** [comment]
I didn't check, just took it from there

**Comment by ilario** [comment]
ok, so let's wait for a confirmation :)

**Comment by ilario** [comment]
I confirm it is needed

**Pull request merged**
