### PR TITLE
add #libremesh-dev channel on Matrix

### PR DESCRIPTION
**Pull request by aparcar**

### CODE REVIEW

**Comment by ilario** [comment]
Can you modify the commit in the following way:

add an explicit indication that for user support the lime-users mailing list is the correct channel

change from
```
https://riot.im/app/#/room/#libremesh-dev:musaik.net[#libremesh-dev] - a public channel for everyone to join and participate
```
to
```
https://riot.im/app/#/room/#libremesh-dev:matrix.guifi.net[#libremesh-dev:matrix.guifi.net] - a public channel for everyone to join and participate on development discussions
```
thanks

**Comment by aparcar** [comment]
@ilario done

**Comment by ilario** [comment]
Maybe we should add the info that the channel is bridged on IRC?

**Comment by ilario** [comment]
I'll add the IRC bridge info, merging.

**Pull request merged**
